#!/usr/bin/env bash

# Credit to ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/Code/ocusell -maxdepth 1 -mindepth 1 -type d`
    items+=`echo -e "\n~/Code/paulredmond"`
    items+=`echo -e "\n~/.dotfiles"`
    items+=`echo -e "\n/tmp"`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected | sed 's/\./_/g'`

tmux switch-client -t =$dirname 2>/dev/null
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname

